run:
  deadline: "10m"
linters:
  disable-all: true
  enable:
    # TODO enable gocritic, maligned, prealloc, typecheck
    - "bodyclose"
    - "deadcode"
    - "errcheck"
    - "gocyclo"
    - "gofmt"
    - "goimports"
    - "golint"
    - "govet"
    - "ineffassign"
    - "megacheck"
    - "misspell"
    - "nakedret"
    - "structcheck"
    - "unconvert"
    - "unparam"
    - "varcheck"
linters-settings:
  errcheck:
    # TODO enable type assertion check
    # check-type-assertions: true
  gocyclo:
    min-complexity: 10
issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
